name: pod lib lint

on:
  push:
    branches: [master]
    paths: 
      - '.github/workflows/pod_lib_lint.yml'
      - '*.podspec'
      - 'Gemfile*'
      - 'Sources/**/*.[ch]'
      - 'Sources/**/*.swift'
  pull_request:
    paths: 
      - '.github/workflows/pod_lib_lint.yml'
      - '*.podspec'
      - 'Gemfile*'
      - 'Sources/**/*.[ch]'
      - 'Sources/**/*.swift'
  workflow_dispatch:

jobs:
  pod_lib_lint:
    name: pod lib lint
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - run: bundle config set path vendor/bundle && bundle install
      - run: bundle exec pod lib lint --verbose
